### ISSUE TITLE
Very cool and useful

### ISSUE THREAD

**Issue by joeblew99** [fortytw2/excalibur#1]
I have a situation where I need to startup various processes on the machine, and the config for one is dependent on the http URL that another starts on.
So your tool seems to be a nice fit.

I looked at the code and could not really see the config dependency in action.

Could you add a small example ? Maybe just 3 programs that say hello, with one starting up and calling into the next from inside itself.

**Comment by fortytw2** [comment]
So right now this is a kinda tiny toy-project, meant to serve as PID1, like SystemD or SysVinit - for your case, I'd recommend taking a look at supervisord or just using your system init to do so (should be pretty straightforward via systemd unit files, I think)

**Comment by joeblew99** [comment]
Oh well thanks anyway.

I think consul with a generator will do the trick
